###

GET http://localhost:3000/student

###

GET http://localhost:3000/student?name=John3

###

GET http://localhost:3000/student/022212389


###

POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "John 444",
    "age": 21,
    "_id": "02221234025"
}

###

PUT http://localhost:3000/student


###

DELETE http://localhost:3000/student

###

GET http://localhost:3000/post